package org.dbs.validator.exception

import org.dbs.application.core.exception.InternalAppException

class GeneralValidatorException(message: String) : InternalAppException(message)
